spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mingledb.cvyuiieo6kzt.us-east-1.rds.amazonaws.com:3306/mingledb?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 12345678

  jpa:  # https://joyerim.tistory.com/6#%E2%96%AA%C2%A0JPA-1
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    key: ${JWT_SECRET_KEY}
    live:
      atk: 300000
      rtk: 3000000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000

    auth-code-expiration-millis: 300000

  batch:
    job:
      enabled: false
      name: importFrequentCustomerJob, reservationStatisticsJob, birthdayReminderJob, purchaseItemJob
    jdbc:
      initialize-schema: always

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

server:
  port: 8080
