version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mingle
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: /scripts/deploy.ps1
      timeout: 60
      runas: ubuntu
  ApplicationStop:
    - location: /scripts/stop.ps1
      timeout: 60
      runas: ubuntu