# 1. 워크플로우의 이름 지정
name: Mingle Backend Build and Push

#2. 워크플로우가 시작될 조건 지정
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest # 3. 실행 환경 지정

    # 4. 실행 스텝 지정
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-actions@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradle

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_TOKEN }}/mingle-backend:latest